"""add default timestamp

Revision ID: 4d7b7be0b711
Revises: 2a084f5cdea7
Create Date: 2026-04-01 00:09:56.431113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7b7be0b711'
down_revision = '2a084f5cdea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_cards', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('card_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_cards', schema=None) as batch_op:
        batch_op.alter_column('card_id',
               existing_type=sa.String(length=100),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=100),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
